export function slugify(text: string): string {
    return text
        .toString()
        .normalize("NFKD")
        .replace(/[\u0300-\u036f]/g, "")
        .toLowerCase()
        .trim()
        .replace(/o‘|o'/g, "o")
        .replace(/g‘|g'/g, "g")
        .replace(/sh/g, "sh")
        .replace(/ch/g, "ch")
        .replace(/ñ/g, "n")
        .replace(/а/g, "a")
        .replace(/б/g, "b")
        .replace(/в/g, "v")
        .replace(/г/g, "g")
        .replace(/д/g, "d")
        .replace(/е/g, "e")
        .replace(/ё/g, "yo")
        .replace(/ж/g, "j")
        .replace(/з/g, "z")
        .replace(/и/g, "i")
        .replace(/й/g, "y")
        .replace(/к/g, "k")
        .replace(/л/g, "l")
        .replace(/м/g, "m")
        .replace(/н/g, "n")
        .replace(/о/g, "o")
        .replace(/п/g, "p")
        .replace(/р/g, "r")
        .replace(/с/g, "s")
        .replace(/т/g, "t")
        .replace(/у/g, "u")
        .replace(/ф/g, "f")
        .replace(/х/g, "x")
        .replace(/ц/g, "s")
        .replace(/ч/g, "ch")
        .replace(/ш/g, "sh")
        .replace(/ъ|ь/g, "")
        .replace(/ю/g, "yu")
        .replace(/я/g, "ya")
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .replace(/-{2,}/g, "-");
}